"""PyDeskUI 0.2: professional, explicit-parent Tk 9 components."""

from .i18n import TranslationContext
from .resources import UnsupportedTkVersionError, check_runtime, load_image, load_svg
from .scheduling import CancelHandle, Scheduler
from .theme import Theme
from .widgets import (
    Button,
    DetailView,
    Dialog,
    Entry,
    FieldSpec,
    Form,
    Item,
    ItemList,
    ProgressView,
    SearchEntry,
)

__version__ = "0.2.0"
__all__ = [
    "Button",
    "Entry",
    "SearchEntry",
    "Item",
    "ItemList",
    "DetailView",
    "FieldSpec",
    "Form",
    "ProgressView",
    "Dialog",
    "Theme",
    "TranslationContext",
    "Scheduler",
    "CancelHandle",
    "load_image",
    "UnsupportedTkVersionError",
    "check_runtime",
    "load_svg",
]

from .widgets import (
    Alert,
    Badge,
    Card,
    Checkbox,
    Combobox,
    ContextMenu,
    DropdownMenu,
    EmptyState,
    Frame,
    Icon,
    Label,
    Popover,
    RadioGroup,
    ScrollArea,
    Select,
    Separator,
    Sheet,
    Sidebar,
    Skeleton,
    Slider,
    Spinbox,
    SplitPane,
    Switch,
    Table,
    Tabs,
    Textarea,
    Toast,
    Toolbar,
    Tooltip,
    Tree,
)

__all__ += [
    "Alert",
    "Badge",
    "Card",
    "Checkbox",
    "Combobox",
    "ContextMenu",
    "DropdownMenu",
    "EmptyState",
    "Frame",
    "Icon",
    "Label",
    "Popover",
    "RadioGroup",
    "ScrollArea",
    "Select",
    "Separator",
    "Sheet",
    "Sidebar",
    "Skeleton",
    "Slider",
    "Spinbox",
    "SplitPane",
    "Switch",
    "Table",
    "Tabs",
    "Textarea",
    "Toast",
    "Toolbar",
    "Tooltip",
    "Tree",
]
